# Generated by Django 2.2.24 on 2022-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wportal', '0007_auto_20220414_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('eligibility', models.CharField(default=0, max_length=100)),
                ('edob', models.DateField()),
                ('rsdob', models.DateField()),
                ('rddob', models.DateField()),
                ('ed', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(choices=[('Select', 'Select'), ('Questionpaper', 'Questionpaper'), ('Notes', 'Notes'), ('Textbook', 'Textbook'), ('Studymaterial', 'Studymaterial')], default=0, max_length=100),
        ),
    ]
