# Generated by Django 2.2.24 on 2022-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wportal', '0008_auto_20220414_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default=0, max_length=300),
        ),
    ]
