# Generated by Django 2.2.24 on 2022-04-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wportal', '0009_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='term',
            field=models.CharField(choices=[('FirstTerm', 'FirstTerm'), ('SecondTerm', 'SecondTerm')], default=' ', max_length=100),
        ),
    ]
